/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Plane: THREE.Mesh;
    Plane_1: THREE.Mesh;
    Light_Wall: THREE.Mesh;
    Bed1: THREE.Mesh;
    Bed2: THREE.Mesh;
    Pillow1: THREE.Mesh;
    Pillow2: THREE.Mesh;
    Bed_Foots: THREE.Mesh;
    Quilt: THREE.Mesh;
    Table: THREE.Mesh;
    Table_Foot1: THREE.Mesh;
    Table_Foot2: THREE.Mesh;
    Plane019: THREE.Mesh;
    Plane019_1: THREE.Mesh;
    IMac_Support: THREE.Mesh;
  };
  materials: {
    Base: THREE.MeshStandardMaterial;
    Floor: THREE.MeshStandardMaterial;
    Light: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
    Fabric: THREE.MeshStandardMaterial;
    Wood: THREE.MeshStandardMaterial;
    ["Shiny Metal"]: THREE.MeshStandardMaterial;
    ["Dark Metal"]: THREE.MeshStandardMaterial;
    Screen: THREE.MeshStandardMaterial;
  };
};

export default function Model({ ...props }: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF("/bedroom.gltf") as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0.16, 0]}>
        <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} />
        <mesh geometry={nodes.Plane_1.geometry} material={materials.Floor} />
      </group>
      <mesh
        geometry={nodes.Light_Wall.geometry}
        material={materials.Light}
        position={[0, 1.68, -2.32]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1.53, 0.4, 0.4]}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.Bed1.geometry}
        material={materials["Material.003"]}
        position={[-0.98, 0.56, 1]}
        scale={[1.15, 1, 1.32]}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.Bed2.geometry}
        material={nodes.Bed2.material}
        position={[-1.05, 0.64, 1]}
        scale={[0.75, 1.65, 0.59]}
      >
        <mesh
          geometry={nodes.Pillow1.geometry}
          material={nodes.Pillow1.material}
          position={[-1.37, 0.17, -0.63]}
          rotation={[0, 0, 2.39]}
          scale={[-0.23, -0.72, -0.53]}
        />
        <mesh
          geometry={nodes.Pillow2.geometry}
          material={nodes.Pillow2.material}
          position={[-1.38, 0.16, 0.79]}
          rotation={[0, 0, 2.39]}
          scale={[-0.23, -0.72, -0.53]}
        />
      </mesh>
      <mesh
        geometry={nodes.Bed_Foots.geometry}
        material={nodes.Bed_Foots.material}
        position={[-0.14, 0.4, 1.66]}
        scale={[0.03, -0.16, 0.03]}
      />
      <mesh
        geometry={nodes.Quilt.geometry}
        material={nodes.Quilt.material}
        position={[-0.95, 0.78, 0.91]}
        scale={1.19}
      />
      <mesh
        geometry={nodes.Table.geometry}
        material={materials.Wood}
        position={[1.82, 1, -1.71]}
        scale={0.49}
      >
        <mesh
          geometry={nodes.Table_Foot1.geometry}
          material={nodes.Table_Foot1.material}
          position={[-4.17, -0.95, -0.09]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          geometry={nodes.Table_Foot2.geometry}
          material={materials["Shiny Metal"]}
          position={[0, -0.94, 3.76]}
        />
      </mesh>
      <group
        position={[0.6, 1.47, -1.67]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[-0.54, 0.28, 0.28]}
      >
        <mesh
          geometry={nodes.Plane019.geometry}
          material={nodes.Plane019.material}
        />
        <mesh
          geometry={nodes.Plane019_1.geometry}
          material={materials.Screen}
        />
      </group>
      <mesh
        geometry={nodes.IMac_Support.geometry}
        material={nodes.IMac_Support.material}
        position={[0.61, 1.31, -1.92]}
        scale={[0.03, 0.3, 0.03]}
      />
    </group>
  );
}

useGLTF.preload("/bedroom.gltf");
